# ==============================================================================
# WISE MoE / Hybrid Inference Runtime — Speed & Quality Tradeoff Evaluator
# Architecture: Evaluates computational output fidelity (numerical equivalence)
# between all-resident Reference Mode and 3-tier Hybrid Execution.
# Evaluates MSE, MAE, MaxAE, Cosine Similarity, and exact match %.
# Semantic language evaluation explicitly reported as UNPROVEN until real model.
# ==============================================================================

from __future__ import annotations

import math
import logging
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, asdict

LOG = logging.getLogger("WISE.Models.Runtime.QualityEvaluator")


@dataclass
class OutputFidelityMetrics:
    total_tokens_compared: int
    exact_matches_count: int
    exact_match_pct: float
    mean_squared_error: float
    mean_absolute_error: float
    max_absolute_error: float
    cosine_similarity: float
    is_computationally_identical: bool
    output_fidelity_score_pct: float
    quality_status: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class MoEQualityEvaluator:
    """
    Evaluator verifying that physical tier movement (NVMe -> RAM -> VRAM)
    does NOT corrupt or alter the mathematical inference result.
    Compares outputs generated by the Hybrid Runtime against Ground-Truth Reference.
    """

    def __init__(self, tolerance: float = 1e-5) -> None:
        self.tolerance = tolerance

    def evaluate(
        self,
        reference_outputs: List[List[float]],
        hybrid_outputs: List[List[float]],
    ) -> OutputFidelityMetrics:
        """
        Calculates numerical fidelity metrics across the entire token sequence.
        """
        if len(reference_outputs) != len(hybrid_outputs):
            raise ValueError(
                f"Output length mismatch: Reference={len(reference_outputs)}, Hybrid={len(hybrid_outputs)}"
            )

        n_tokens = len(reference_outputs)
        if n_tokens == 0:
            return OutputFidelityMetrics(
                total_tokens_compared=0,
                exact_matches_count=0,
                exact_match_pct=100.0,
                mean_squared_error=0.0,
                mean_absolute_error=0.0,
                max_absolute_error=0.0,
                cosine_similarity=1.0,
                is_computationally_identical=True,
                output_fidelity_score_pct=100.0,
                quality_status="COMPUTATIONALLY_IDENTICAL_100%",
            )

        exact_matches = 0
        total_squared_error = 0.0
        total_abs_error = 0.0
        max_abs_error = 0.0
        total_cosine_sim = 0.0
        total_elements = 0

        for ref_vec, hyb_vec in zip(reference_outputs, hybrid_outputs):
            dim = len(ref_vec)
            vec_identical = True

            dot = 0.0
            norm_ref = 0.0
            norm_hyb = 0.0

            for r, h in zip(ref_vec, hyb_vec):
                diff = abs(r - h)
                total_squared_error += diff ** 2
                total_abs_error += diff
                if diff > max_abs_error:
                    max_abs_error = diff
                if diff > self.tolerance:
                    vec_identical = False

                dot += r * h
                norm_ref += r * r
                norm_hyb += h * h
                total_elements += 1

            if vec_identical:
                exact_matches += 1

            # Cosine similarity for this token
            denom = math.sqrt(norm_ref) * math.sqrt(norm_hyb)
            cos_sim = (dot / denom) if denom > 1e-9 else (1.0 if norm_ref == norm_hyb == 0 else 0.0)
            total_cosine_sim += max(-1.0, min(1.0, cos_sim))

        mse = total_squared_error / max(1, total_elements)
        mae = total_abs_error / max(1, total_elements)
        avg_cos = total_cosine_sim / n_tokens
        exact_pct = (exact_matches / n_tokens) * 100.0
        is_identical = (exact_matches == n_tokens) and (max_abs_error <= self.tolerance)

        fidelity_score = round(avg_cos * 100.0, 2)
        status = "COMPUTATIONALLY_IDENTICAL_100%" if is_identical else (
            f"NUMERICAL_DRIFT_DETECTED (MaxAE={max_abs_error:.6f})"
        )

        LOG.info(
            "Quality Evaluation: Tokens=%d, ExactMatch=%.1f%%, MSE=%.2e, CosineSim=%.4f (%s)",
            n_tokens, exact_pct, mse, avg_cos, status,
        )

        return OutputFidelityMetrics(
            total_tokens_compared=n_tokens,
            exact_matches_count=exact_matches,
            exact_match_pct=round(exact_pct, 2),
            mean_squared_error=mse,
            mean_absolute_error=mae,
            max_absolute_error=max_abs_error,
            cosine_similarity=round(avg_cos, 4),
            is_computationally_identical=is_identical,
            output_fidelity_score_pct=fidelity_score,
            quality_status=status,
        )


class SemanticQualityEvaluator:
    """
    Interface for high-level language semantic benchmarking (MMLU, HumanEval, Tool-Calling).
    Strictly reports UNPROVEN in Phase P1.4-A because real 30B/40B weights are not yet installed.
    Zero fabricated language-model intelligence.
    """

    def __init__(self, real_model_available: bool = False) -> None:
        self.real_model_available = real_model_available

    def evaluate_semantic_quality(self) -> Dict[str, Any]:
        if not self.real_model_available:
            return {
                "semantic_benchmarking_status": "UNPROVEN — REAL LANGUAGE MODEL REQUIRED",
                "real_model_installed": False,
                "mmlU_score": None,
                "tool_call_accuracy": None,
                "hallucination_rate": None,
                "explanation": (
                    "Phase P1.4-A establishes and validates the 3-tier memory and compute runtime architecture. "
                    "Per strict instructions, no 30B/40B language model weights were downloaded. "
                    "Semantic evaluation will be performed in Phase P1.4-B when weights are integrated."
                ),
            }
        else:
            return {
                "semantic_benchmarking_status": "EVALUATION_ACTIVE",
                "real_model_installed": True,
            }
